---
driver:
  name: vagrant
  customize: 
    memory: 3072

transport:
  name: ssh
  connection_retries: 12
  connection_retry_sleep: 15

provisioner:
  name: chef_zero
  root_path: /home/vagrant/kitchen
  always_update_cookbooks: true
  retry_on_exit_code:
    - 35 # exit code signaling that the node is rebooting
  client_rb:
    client_fork: false # forked instances don't return the real exit code

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  # - name: centos-7
  # - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[box::default]
    verifier:
      inspec_tests:
        - test/integration/mssql
        - test/integration/default
        - test/integration/base
        - test/integration/rvm
        - test/integration/postgresql
        - test/integration/java
        - test/integration/webkit
        - test/integration/commandbox
    attributes:

